---
- name: Start web server
  command:
    "python3.8 -m http.server {{ serve_artifacts_bind_port }} --directory {{ serve_artifacts_base_path }}"
  # Fire and forget for __timeout__ seconds
  async: "{{ serve_artifacts_timeout }}"
  poll: 0
